import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import AuthProvider from "@/lib/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession() ; 
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <AuthProvider session={session} >
        <NavBar /> 
        {/*NavBar needs to be inside AuthProvider because AuthProvider has SessionProvider
        and any component (like NavBar) that is using the useSession hook needs to be wrapped
        inside SessionProvider 
         */}
        {children} 
        </AuthProvider>
      </body>
    </html>
  );
}
